### ISSUE TITLE
Plugin is crashing when trying to read airTemperature

### ISSUE THREAD

**Issue by viamin** [viamin/homebridge-rise-garden#62]
```
[1/3/2023, 4:55:02 PM] [Rise Garden] Error getting airTemperature reading from Rise API
Error: HAP Status Error: -70402
    at new HapStatusError (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/hapStatusError.ts:17:5)
    at RiseGardenAirTemperature.getTemperature (/homebridge/node_modules/homebridge-rise-garden/src/temperature.ts:84:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
However this log was generated around 6:10pm, so there's also a timestamp issue...

**Comment by viamin** [comment]
Looks like that was the correct timestamp - there is also this:
```
[1/3/2023, 4:54:50 PM] Homebridge v1.6.0 (HAP v0.11.0) (Rise Garden) is running on port 30130.

/homebridge/node_modules/homebridge-rise-garden/node_modules/axios/lib/core/AxiosError.js:89
  AxiosError.call(axiosError, error.message, code, config, request, response);
             ^
Error: Hostname/IP does not match certificate's altnames: Host: prod-api.risegds.com. is not in the cert's altnames: DNS:exfoasaplatform.com, DNS:*.exfoasaplatform.com
    at Function.AxiosError.from (/homebridge/node_modules/homebridge-rise-garden/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/homebridge/node_modules/homebridge-rise-garden/node_modules/axios/lib/adapters/http.js:526:25)
    at RedirectableRequest.emit (node:events:390:28)
    at ClientRequest.eventHandlers.<computed> (/homebridge/node_modules/homebridge-rise-garden/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:390:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
It looks like the latest release is working, though. I'm seeing temperatures in HomeKit with plugin v1.1.2.
(Note the timestamp: `[1/3/2023, 6:08:29 PM] [Homebridge UI] Running Command: npm install --save homebridge-rise-garden@1.1.2`)

**Comment by viamin** [comment]
Closing
