### ISSUE TITLE
Plugin is reported as unresponsive in Home app

### ISSUE THREAD

**Issue by viamin** [viamin/homebridge-rise-garden#63]
It looks like the plugin may be failing to load altogether:
```
[1/7/2023, 1:15:35 PM] Homebridge v1.6.0 (HAP v0.11.0) (Rise Garden) is running on port 30130.

/homebridge/node_modules/homebridge-rise-garden/node_modules/axios/lib/core/AxiosError.js:89
  AxiosError.call(axiosError, error.message, code, config, request, response);
             ^
Error: connect ETIMEDOUT 3.128.218.254:443
    at Function.AxiosError.from (/homebridge/node_modules/homebridge-rise-garden/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/homebridge/node_modules/homebridge-rise-garden/node_modules/axios/lib/adapters/http.js:526:25)
    at RedirectableRequest.emit (node:events:390:28)
    at ClientRequest.eventHandlers.<computed> (/homebridge/node_modules/homebridge-rise-garden/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:390:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
`axios` was recently updated in https://github.com/viamin/homebridge-rise-garden/pull/55 so that is a possible culprit.

**Comment by viamin** [comment]
There's also this error which hits about 10 seconds before the one in the description:
```
[1/7/2023, 1:15:24 PM] Homebridge v1.6.0 (HAP v0.11.0) (Rise Garden) is running on port 30130.

/homebridge/node_modules/homebridge-rise-garden/node_modules/axios/lib/core/AxiosError.js:89
  AxiosError.call(axiosError, error.message, code, config, request, response);
             ^
Error: Hostname/IP does not match certificate's altnames: Host: prod-api.risegds.com. is not in the cert's altnames: DNS:exfoasaplatform.com, DNS:*.exfoasaplatform.com
    at Function.AxiosError.from (/homebridge/node_modules/homebridge-rise-garden/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/homebridge/node_modules/homebridge-rise-garden/node_modules/axios/lib/adapters/http.js:526:25)
    at RedirectableRequest.emit (node:events:390:28)
    at ClientRequest.eventHandlers.<computed> (/homebridge/node_modules/homebridge-rise-garden/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:390:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
```

**Comment by viamin** [comment]
Maybe a change on Rise's end

**Comment by viamin** [comment]
It's intermittent, so maybe it was an issue with the servers. An expired certificate?
